### ISSUE TITLE
Doubt about hexo's multilanguages 

### ISSUE THREAD

**Issue by Karolinehc** [levblanc/hexo-theme-aero-dual#11]
Hey there! Few theme are built with multi languages configuration I have noticed that your theme has been configurated for it (because I'm native speaker Spanish and it has been shown the translate option for my mother language, so I would like to know that methodology have you used, step by step, please. Thanks ;)

**Comment by levblanc** [comment]
Hi,

Actually I didn't do any Spanish translation configuration in my theme. 

I am guessing that's the browser's option for translating languages according to your IP, 
or other methods they use to detect your location.

I came across such options when browsing websites in other languages as well.

In case you want to use my theme and configure it to Spanish: 

After downloading my theme to your blog's theme folder,
1. add a `spanish.yml` (or you may name it whatever you want) file in the `languages` folder.
2. copy everything in the `en.yml` and paste them to the above created file.
3. modify the value (as `yml` file contents are `key: value` pairs) to Spanish equivalents. 
4. in your blog's `_config.yml`, set the `language` option according to the name of your new language file.

**Comment by Karolinehc** [comment]
谢 谢        (  xiè xie!)       ;)
