### ISSUE TITLE
代码高亮不正常

### ISSUE THREAD

**Issue by Evyde** [levblanc/hexo-theme-aero-dual#19]
如图：
![image](https://user-images.githubusercontent.com/9302540/41467577-9eab7980-70d9-11e8-8c4f-35061dd2305b.png)
```c++
#include <iostream>
int main()
{
  using namespace std::cout;
  using namespace std::cin;
  using namespace std::endl;

  int dogs = 1;

  cout << "I have " << dogs << " dogs." << endl;
  cout << "Then you need to add some dogs, input the number which you want to add: ";
  cin >> dogs;
  dogs += 1;
  cout << "Now I have " << dogs << " dogs, thx." << endl;
  return 0;
}
```
同样的写法，在github就能高亮。
地址：https://i.r6up.win/

**Comment by levblanc** [comment]
已更新 highlight.js 的bundle，让它能够识别更多语言。拉取最新的代码试试。

如果可以的话就回来关闭这个issue吧。

**Comment by Evyde** [comment]
只能说好一些了，但是对于很多代码仍然不支持高亮，如图，C++和Java的关键字竟然都没有高亮。。。
![image](https://user-images.githubusercontent.com/9302540/42330903-bbd2937c-80a6-11e8-89ce-399803e429e0.png)
![image](https://user-images.githubusercontent.com/9302540/42330916-c60693ca-80a6-11e8-81d8-de154fd3075a.png)
但是这个问题似乎是间歇性的，如图，同一片文章内都是Java这个高亮就没有问题：
![image](https://user-images.githubusercontent.com/9302540/42330868-a2d1e7e2-80a6-11e8-8550-b82c37cdaa02.png)
可能是玄学问题。

**Comment by levblanc** [comment]
我发现highlight js会自己检测代码类型，[官方页面在这](https://highlightjs.org/usage/)

![image](https://user-images.githubusercontent.com/4057887/42920363-d704af7a-8b48-11e8-8271-ff5a361cc0e5.png)

（虽然它说可以自定义，然而hexo这边是直接从markdown生成的，我控制不了代码块的class……）

你的第一段截图代码，它认为是R…… （即使我本地尝试的时候，在markdown里面已经声明是java）

![image](https://user-images.githubusercontent.com/4057887/42920283-61720a3c-8b48-11e8-8675-5b2904e93693.png)

我下载的bundle里面应该是没有R吧，即使有，高亮出来跟你的代码应该对不上的，因为本来类型就错了。

有一个比较折腾的解决方法，就是使用hexo自带的landscape主题的代码高亮来替换我的方案：

1. 复制 landscape 的 [highlight.styl](https://github.com/hexojs/hexo-theme-landscape/blob/master/source/css/_partial/highlight.styl) 

（其中有些变量在[_variables.styl](https://github.com/hexojs/hexo-theme-landscape/blob/master/source/css/_variables.styl)，缺少的话编译的时候会报错，报哪个出错，就过去复制哪个，就行了。我这边尝试过，补上`font-size`，`line-height`，`font-mono`，`article-padding`这几个基本就ok了。）

2. 替换我的 code.styl (areo_dual/source/css/_typography/code.styl) 里面的内容，然后把其中的`.article-entry` class 改成`.post-content`

3. 把 highlight.js 的引入屏蔽（注释 aero-dual/layout/_partial/after-footer.ejs 里面的全部内容）

> 写到这里，我有一个大胆的猜想，就是直接屏蔽我的 code.styl 和 after-footer.ejs 内容，然后直接在 html-head.ejs 里面引入github的样式，或许也是可行的。github的样式在人家的文章里面看到有这个`<link rel="stylesheet" href="//cdn.bootcss.com/highlight.js/9.2.0/styles/github.min.css">`，还有[这里的CDN地址](https://cdnjs.com/libraries/github-markdown-css)，如果速度慢，就整个拿下来放到项目里吧

上面这三个步骤折腾完毕的效果：

![image](https://user-images.githubusercontent.com/4057887/42921078-7b1b661e-8b4c-11e8-9606-2a10e9210c69.png)

希望能对你有所帮助，以上！

**Comment by Evyde** [comment]
感谢，我会试一试的。
不过希望您写的这篇文章可以加入wiki。
