### ISSUE TITLE
how could I add the Widget or disqus ???  Thank you!

### ISSUE THREAD

**Issue by evawyf** [levblanc/hexo-theme-aero-dual#2]
I tried to add the `disqus_shortname: short-name` in `_config.yml` but does not work. 
Thanks!

**Comment by levblanc** [comment]
Sorry for the late response.

Tweaking the UI had taken up an unexpected large amount of my spear time, and I think this is all I can give at the moment. Adding support of other widgets is a maybe, depending on my upcoming workload... (Will update a notifier of not supporting widgets and disqus in the README file). 

Checking out other themes may help, and feel free to modify the theme by yourself :)
