### ISSUE TITLE
摘要，标签和分类问题

### ISSUE THREAD

**Issue by TRHX** [levblanc/hexo-theme-aero-dual#20]
本人没有网站开发相关基础，在这方面知识为零，想请问前辈运用该主题后写文章该如何添加摘要，标签和分类，小白一个，望前辈解答一下，万分感谢！

**Comment by levblanc** [comment]
在你的`md`文件顶部添加 front-matter，具体可以参考 [hexo 官方文档](https://hexo.io/zh-cn/docs/front-matter) ，并推荐阅读官网中的其它操作说明。

```
title: 文章题目
author: 文章作者
date: 文章创建时间
categories: [文章类别]
tags: [文章tag]
---

文章摘要

<!-- more -->  // <= front matter之后，这一行注释之前的文字都会变成摘要

文章内容
```
