### ISSUE TITLE
自定义Post's Banner Image在GitHub pages上不起作用？

### ISSUE THREAD

**Issue by wylighting** [levblanc/hexo-theme-aero-dual#4]
按照readme中的方法进行配置文章上的自定义图片。Post's Banner Image放在了/sources/images下，但是deploy到GitHub pages 之后不起作用（因为这个文件夹没上传）。在本地模式下是可以起作用的。所以请问有方法解决这个问题？（ 后来把图片放在themes里面的img下貌似就成功了 = =）

**Comment by levblanc** [comment]
@swordigo1995 
除了放置图片到博客的`/source/<your-image-folder>`以外，
在想要改变banner的那篇post，front-matter（也就是最顶上那几行post信息）里面还要增加一行：

`cover: /<your-image-folder>/<image-name>.jpg` 

(当然，图片格式可以是任意的，这里的例子用jpg而已。
同时，记得`source`下自己新建的**图片文件夹**以及**图片**的名称，在这行要写对)

在themes里面改变的是整个博客的所有默认banner。

同时也谢谢你的反馈，我轻微修改了一下readme。
可能`cover`这一行之前写得不是很明显，才造成你的困惑。
