### ISSUE TITLE
How to change code hightlight style to monikai-sublime.styl?

### ISSUE THREAD

**Issue by lucasjinreal** [levblanc/hexo-theme-aero-dual#8]
I see there has such style in css, but how to enable it , the original is some kind of incompatible with the whole tire theme.

**Comment by levblanc** [comment]
You will have to go to `aero-dual/source/css/sytle.<dark/light>.styl` , and change the highlight line to `@import '_typography/highlight.monikai-sublime'`. 

I put three highlight stylesheets in the `_typography` folder, but actually, you can pick the one you want in highlight.js website and put it here, then import it.

 If I remember it right, highlight.js provides `css` files, you may have to convert it to `.styl` file with online converting tools or other helpers.

**Comment by lucasjinreal** [comment]
thanks, I find that. BTW, this theme is fabulous, strongly recomend keep on developing and make it perfect!
